# Generated by Django 4.1.7 on 2023-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('header', models.CharField(max_length=128, verbose_name='Название мероприятия')),
                ('date', models.DateTimeField(verbose_name='Дата и время мероприятия')),
                ('location', models.CharField(max_length=256, verbose_name='Адрес мероприятия')),
                ('description', models.TextField()),
                ('social_link1', models.URLField(blank=True, null=True)),
                ('social_link2', models.URLField(blank=True, null=True)),
                ('event_tags', models.ManyToManyField(to='events.eventtag', verbose_name='тэги мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
