# Generated by Django 4.1.7 on 2023-05-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32)),
                ('day_of_week', models.CharField(blank=True, max_length=32, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.studentgroup')),
            ],
            options={
                'verbose_name': 'дневное расписание',
                'verbose_name_plural': 'дневные расписания',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='PreviousWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.SmallIntegerField()),
                ('days', models.ManyToManyField(to='schedule_models.dayschedule')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.studentgroup')),
            ],
            options={
                'verbose_name': 'предыдущую неделю',
                'verbose_name_plural': 'предыдущие недели',
            },
        ),
        migrations.CreateModel(
            name='NextWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.SmallIntegerField()),
                ('group', models.CharField(max_length=128, null=True)),
                ('days', models.ManyToManyField(to='schedule_models.dayschedule')),
            ],
            options={
                'verbose_name': 'следующую неделю',
                'verbose_name_plural': 'следующие недели',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('teacher', models.ManyToManyField(to='schedule_models.teacher', verbose_name='Учителя')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='lessons',
            field=models.ManyToManyField(related_name='lesson_day', to='schedule_models.lesson'),
        ),
        migrations.CreateModel(
            name='CurrentWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.SmallIntegerField()),
                ('days', models.ManyToManyField(to='schedule_models.dayschedule')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.studentgroup')),
            ],
            options={
                'verbose_name': 'текущая неделя',
                'verbose_name_plural': 'текущие недели',
            },
        ),
    ]
