# Generated by Django 4.1.7 on 2023-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
